[package]
name = "skill_token"
version = "1.0.0"
authors = ["Skill Token Developer"]

[addresses]
skill_token = "0x2ea4f00c416f7e2f20d6a66846b95d23e0da3436bf3e5a74e9d7bacaf7344882"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }